import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { FormEvent, useState } from "react";
import { ArrowLeft, GraduationCap } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
export const Route = createFileRoute("/auth")({ head: () => ({ meta: [{ title: "Sign in — SkillSwap" }, { name: "description", content: "Sign in or create your SkillSwap student account." }, { property: "og:title", content: "Sign in — SkillSwap" }, { property: "og:description", content: "Join your campus skill exchange community." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AuthPage });
function AuthPage() { const [mode, setMode] = useState<"signin"|"signup">("signin"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const navigate = useNavigate();
 const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setNotice(""); setBusy(true); if (password.length < 8) { setError("Use at least 8 characters for your password."); setBusy(false); return; } if (mode === "signup" && name.trim().length < 2) { setError("Enter your full name."); setBusy(false); return; } const result = mode === "signin" ? await supabase.auth.signInWithPassword({ email: email.trim(), password }) : await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim() }, emailRedirectTo: `${window.location.origin}/auth` } }); setBusy(false); if (result.error) { setError(result.error.message); return; } if (mode === "signup" && !result.data.session) { setNotice("Check your email to confirm your account, then sign in."); return; } await navigate({ to: "/dashboard" }); };
 const google = async () => { const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: window.location.origin }); if (result.error) setError(result.error.message); else if (!result.redirected) await navigate({ to: "/dashboard" }); };
 return <main className="grid min-h-screen bg-background lg:grid-cols-[1.05fr_.95fr]"><section className="hidden bg-primary p-14 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><Link to="/" className="flex items-center gap-2 font-semibold"><ArrowLeft className="h-4 w-4" />Back to SkillSwap</Link><div><GraduationCap className="mb-6 h-12 w-12" /><h1 className="max-w-xl text-5xl font-bold leading-tight">Your campus is full of people worth learning from.</h1><p className="mt-5 max-w-lg text-lg text-primary-foreground/75">Trade skills, build confidence, and make useful connections beyond the classroom.</p></div><p className="text-sm text-primary-foreground/70">Built for curious students.</p></section><section className="flex items-center justify-center p-5 sm:p-10"><Card className="w-full max-w-md border-0 shadow-elevated"><CardHeader><CardTitle className="text-2xl">{mode === "signin" ? "Welcome back" : "Join SkillSwap"}</CardTitle><CardDescription>{mode === "signin" ? "Sign in to continue your exchanges." : "Create your student account in a minute."}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{mode === "signup" && <div className="space-y-2"><Label htmlFor="name">Full name</Label><Input id="name" value={name} onChange={(e) => setName(e.target.value)} maxLength={100} required /></div>}<div className="space-y-2"><Label htmlFor="email">College email</Label><Input id="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} maxLength={255} required /></div><div className="space-y-2"><Label htmlFor="password">Password</Label><Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} maxLength={72} required /></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p className="rounded-md bg-success-soft p-3 text-sm text-success">{notice}</p>}<Button className="w-full" size="lg" disabled={busy}>{busy ? "Please wait…" : mode === "signin" ? "Sign in" : "Create account"}</Button></form><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />OR<span className="h-px flex-1 bg-border" /></div><Button variant="outline" className="w-full" size="lg" onClick={google}>Continue with Google</Button><p className="mt-6 text-center text-sm text-muted-foreground">{mode === "signin" ? "New here?" : "Already a member?"} <button type="button" className="font-semibold text-primary" onClick={() => { setMode(mode === "signin" ? "signup" : "signin"); setError(""); setNotice(""); }}>{mode === "signin" ? "Create an account" : "Sign in"}</button></p></CardContent></Card></section></main>; }
