import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, GraduationCap, Handshake, Sparkles } from "lucide-react";
import { appDataQuery } from "@/lib/app-data";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/app/page-header";
import { StatusBadge } from "@/components/app/status-badge";
export const Route = createFileRoute("/_authenticated/dashboard")({ loader: ({ context }) => context.queryClient.ensureQueryData(appDataQuery()), head: () => ({ meta: [{ title: "Dashboard — SkillSwap" }, { name: "description", content: "Your SkillSwap activity and campus exchanges." }, { property: "og:title", content: "Dashboard — SkillSwap" }, { property: "og:description", content: "Your student skill exchange dashboard." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Dashboard });
function Dashboard() { const { data } = useSuspenseQuery(appDataQuery()); const mine = data.profileSkills.filter((s) => s.profile_id === data.userId); const requests = data.requests; const active = requests.filter((r) => r.status === "accepted"); const stats = [{ label: "Total skills", value: mine.length, icon: Sparkles }, { label: "Teaching", value: mine.filter((s) => s.direction === "teaching").length, icon: GraduationCap }, { label: "Learning", value: mine.filter((s) => s.direction === "learning").length, icon: BookOpen }, { label: "Pending", value: requests.filter((r) => r.status === "pending").length, icon: Clock3 }, { label: "Accepted", value: active.length, icon: Handshake }, { label: "Completed", value: requests.filter((r) => r.status === "completed").length, icon: CheckCircle2 }]; const skillName = (id: string | null) => data.skills.find((s) => s.id === id)?.name ?? "Skill"; return <div className="space-y-8"><PageHeader eyebrow="Your campus exchange" title="Dashboard" description="Stay on top of what you're learning, teaching, and building with your peers." action={<Button asChild><Link to="/discover">Find a skill <ArrowRight /></Link></Button>} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{stats.map(({ label, value, icon: Icon }) => <Card key={label} className="shadow-soft"><CardContent className="p-4"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-primary" /><span className="text-2xl font-bold">{value}</span></div><p className="mt-4 text-xs font-medium text-muted-foreground">{label}</p></CardContent></Card>)}</div><section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Recent exchanges</h2><Button asChild variant="ghost"><Link to="/exchanges">View all <ArrowRight /></Link></Button></div>{active.length === 0 ? <div className="rounded-lg border border-dashed p-10 text-center"><Handshake className="mx-auto h-9 w-9 text-muted-foreground" /><h3 className="mt-4 font-semibold">No accepted exchanges yet</h3><p className="mt-1 text-sm text-muted-foreground">Discover a student and send your first request.</p></div> : <div className="grid gap-3 lg:grid-cols-2">{active.slice(0,4).map((item) => <Card key={item.id} className="shadow-soft"><CardContent className="flex items-center justify-between gap-4 p-5"><div><p className="font-semibold">Learning: {skillName(item.requested_skill_id)}</p><p className="mt-1 text-sm text-muted-foreground">Teaching: {skillName(item.offered_skill_id)}</p></div><StatusBadge status={item.status} /></CardContent></Card>)}</div>}</section></div>; }
