import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { CheckCircle2, PartyPopper, Play, RotateCw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { appDataQuery } from "@/lib/app-data";
import { updateExchange } from "@/lib/app-data.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Slider } from "@/components/ui/slider";
import { ProfileAvatar } from "@/components/app/profile-avatar";
import { PageHeader } from "@/components/app/page-header";
export const Route = createFileRoute("/_authenticated/exchanges")({ loader: ({ context }) => context.queryClient.ensureQueryData(appDataQuery()), head: () => ({ meta: [{ title: "Exchanges — SkillSwap" }, { name: "description", content: "Track progress on accepted and completed skill exchanges." }, { property: "og:title", content: "Exchanges — SkillSwap" }, { property: "og:description", content: "Track your skill exchange progress." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Exchanges });
function Exchanges() { const { data } = useSuspenseQuery(appDataQuery()); const items = data.requests.filter((r) => r.status === "accepted" || r.status === "completed"); return <div className="space-y-8"><PageHeader eyebrow="Learning progress" title="Skill exchanges" description="Move each accepted exchange from a good intention to a completed goal." />{items.length === 0 ? <div className="rounded-lg border border-dashed p-12 text-center"><CheckCircle2 className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-4 font-semibold">Complete your first skill exchange to see it here.</h2><p className="mt-1 text-sm text-muted-foreground">Accepted requests become trackable exchanges.</p></div> : <div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <ExchangeCard key={item.id} item={item} data={data} />)}</div>}</div>; }
function ExchangeCard({ item, data }: { item: (typeof data.requests)[number]; data: Awaited<ReturnType<typeof import("@/lib/app-data.functions").getAppData>> }) { const [value, setValue] = useState(item.progress); const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: updateExchange, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["student-exchange"] }); toast.success(value === 100 ? "Exchange completed!" : "Progress updated"); }, onError: (error) => toast.error(error.message) }); const otherId = item.requester_id === data.userId ? item.recipient_id : item.requester_id; const person = data.profiles.find((p) => p.id === otherId); const requested = data.skills.find((s) => s.id === item.requested_skill_id)?.name; const offered = data.skills.find((s) => s.id === item.offered_skill_id)?.name ?? "Open exchange"; const completed = item.status === "completed"; const stage = completed ? "Completed" : value === 0 ? "Start" : "In Progress"; return <Card className="shadow-soft"><CardContent className="p-6"><div className="flex items-center gap-3"><ProfileAvatar name={person?.full_name ?? "Student"} path={person?.avatar_path} /><div><h2 className="font-bold">{person?.full_name || "Student"}</h2><p className="text-xs text-muted-foreground">Skill exchange partner</p></div></div><div className="mt-6 grid grid-cols-2 gap-4 rounded-md bg-muted p-4 text-sm"><div><span className="text-muted-foreground">Learning</span><strong className="mt-1 block">{requested}</strong></div><div><span className="text-muted-foreground">Teaching</span><strong className="mt-1 block">{offered}</strong></div></div><div className="mt-6 flex items-center justify-between"><span className="font-semibold">Skill Exchange Progress</span><strong>{completed ? 100 : value}%</strong></div><Progress value={completed ? 100 : value} className="mt-3" />{completed ? <div className="mt-5 flex items-center gap-3 rounded-md bg-success-soft p-4 font-semibold text-success"><PartyPopper className="h-5 w-5" />Exchange Completed 🎉</div> : <><Slider className="mt-6" value={[value]} min={0} max={100} step={10} onValueChange={([next]) => setValue(next ?? 0)} /><div className="mt-5 flex items-center justify-between"><span className="inline-flex items-center gap-2 text-sm font-semibold text-primary">{value === 0 ? <Play className="h-4 w-4" /> : <RotateCw className="h-4 w-4" />}{stage}</span><Button disabled={value === item.progress || mutation.isPending} onClick={() => mutation.mutate({ data: { id: item.id, action: "progress", progress: value } })}>Update progress</Button></div></>}</CardContent></Card>; }
