import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { Bell, CheckCheck } from "lucide-react";
import { appDataQuery } from "@/lib/app-data";
import { markNotificationsRead } from "@/lib/app-data.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/app/page-header";
export const Route = createFileRoute("/_authenticated/notifications")({ loader: ({ context }) => context.queryClient.ensureQueryData(appDataQuery()), head: () => ({ meta: [{ title: "Notifications — SkillSwap" }, { name: "description", content: "Your important SkillSwap updates." }, { property: "og:title", content: "Notifications — SkillSwap" }, { property: "og:description", content: "Your important SkillSwap updates." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Notifications });
function Notifications() { const { data } = useSuspenseQuery(appDataQuery()); const queryClient = useQueryClient(); const mark = useMutation({ mutationFn: markNotificationsRead, onSuccess: () => queryClient.invalidateQueries({ queryKey: ["student-exchange"] }) }); return <div className="space-y-8"><PageHeader eyebrow="Updates" title="Notifications" description="Important activity from your requests and exchanges." action={data.notifications.some((n) => !n.read_at) ? <Button variant="outline" onClick={() => mark.mutate()} disabled={mark.isPending}><CheckCheck />Mark all read</Button> : undefined} />{data.notifications.length === 0 ? <div className="rounded-lg border border-dashed p-12 text-center"><Bell className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-4 font-semibold">You're all caught up</h2><p className="mt-1 text-sm text-muted-foreground">New requests and exchange updates will appear here.</p></div> : <div className="space-y-3">{data.notifications.map((item) => <Card key={item.id} className={item.read_at ? "shadow-soft" : "border-primary/30 bg-primary-soft/40 shadow-soft"}><CardContent className="flex gap-4 p-5"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-primary" /><div><h2 className="font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.body}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</p></div></CardContent></Card>)}</div>}</div>; }
