import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { Check, Inbox, X } from "lucide-react";
import { toast } from "sonner";
import { appDataQuery } from "@/lib/app-data";
import { updateExchange } from "@/lib/app-data.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ProfileAvatar } from "@/components/app/profile-avatar";
import { StatusBadge } from "@/components/app/status-badge";
import { PageHeader } from "@/components/app/page-header";
export const Route = createFileRoute("/_authenticated/requests")({ loader: ({ context }) => context.queryClient.ensureQueryData(appDataQuery()), head: () => ({ meta: [{ title: "Requests — SkillSwap" }, { name: "description", content: "Manage incoming and outgoing skill exchange requests." }, { property: "og:title", content: "Requests — SkillSwap" }, { property: "og:description", content: "Manage your skill exchange requests." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Requests });
function Requests() { const { data } = useSuspenseQuery(appDataQuery()); const queryClient = useQueryClient(); const mutation = useMutation({ mutationFn: updateExchange, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["student-exchange"] }); toast.success("Request updated"); }, onError: (error) => toast.error(error.message) }); const incoming = data.requests.filter((r) => r.recipient_id === data.userId); const outgoing = data.requests.filter((r) => r.requester_id === data.userId); const list = (items: typeof incoming, incomingMode: boolean) => items.length === 0 ? <Empty /> : <div className="space-y-3">{items.map((item) => { const otherId = incomingMode ? item.requester_id : item.recipient_id; const person = data.profiles.find((p) => p.id === otherId); const requested = data.skills.find((s) => s.id === item.requested_skill_id)?.name; const offered = data.skills.find((s) => s.id === item.offered_skill_id)?.name; return <Card key={item.id} className="shadow-soft"><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><ProfileAvatar name={person?.full_name ?? "Student"} path={person?.avatar_path} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{person?.full_name || "Student"}</h2><StatusBadge status={item.status} /></div><p className="mt-1 text-sm">Learning <strong>{requested}</strong>{offered ? <> · Teaching <strong>{offered}</strong></> : null}</p>{item.message && <p className="mt-2 line-clamp-2 text-sm text-muted-foreground">“{item.message}”</p>}</div>{incomingMode && item.status === "pending" && <div className="flex gap-2"><Button variant="outline" onClick={() => mutation.mutate({ data: { id: item.id, action: "reject" } })}><X />Reject</Button><Button onClick={() => mutation.mutate({ data: { id: item.id, action: "accept" } })}><Check />Accept</Button></div>}</CardContent></Card>; })}</div>; return <div className="space-y-8"><PageHeader eyebrow="Connections" title="Exchange requests" description="Review new requests and keep track of the exchanges you've proposed." /><Tabs defaultValue="incoming"><TabsList><TabsTrigger value="incoming">Incoming ({incoming.length})</TabsTrigger><TabsTrigger value="outgoing">Outgoing ({outgoing.length})</TabsTrigger></TabsList><TabsContent value="incoming" className="mt-5">{list(incoming, true)}</TabsContent><TabsContent value="outgoing" className="mt-5">{list(outgoing, false)}</TabsContent></Tabs></div>; }
function Empty() { return <div className="rounded-lg border border-dashed p-12 text-center"><Inbox className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-4 font-semibold">You don't have any exchange requests yet.</h2><p className="mt-1 text-sm text-muted-foreground">Requests you send or receive will appear here.</p></div>; }
